# Seattle Car Accident Severity

Description of the problem 

Statistics
Seattle is a city in Washington State, as of 2020, it has a total metro area population of 3.4 million residents. In the year of 2016, an average of 450,000 vehicles was announce in the State Census. Even with two metro system providers the city is overpopulated. The traffic situation motivated the population to buy car and as a result use this method of transportation to commute. The increase in car ownership raised the numbers of accidents on the road. Seattle is city surrounded by water and mountains brings severe weather changes like rain and fog and snow into the city, statically, this weather factors turns out in more car accidents 

Worldwide situation 
Car accidents turns out in a very serious situation, bring to reality a lot of issues, example, deaths health conditions, waste of money to the insurance companies, governments and population. According to 2017 WSDOT data, a car accident occurs every 4 minutes and a person dies due to a car crash every 20 hours in the state of Washington. The Seattle Severity Car Accident project pretends to predict how severity of accidents can be reduced based on a few factors.

Stakeholders 
Minimizing the number of car accidents can be beneficial for the population, insurance companies, and local governments. A lot of local governments work in a daily basis to prevent this king of accidents, announcing weather conditions in the area, conditions in the road or even announcing car accidents ahead, in this way they help to prevent more accidents.

In [3]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_3ff27e413aed4ba787438783bd8901d9 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='LNje49-FnW_K-gI3_ZaEFShUw1erhSweZfiaH1O3EnmE',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

body = client_3ff27e413aed4ba787438783bd8901d9.get_object(Bucket='a-donotdelete-pr-i8k6hea1resvdj',Key='Data-Collisions.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df = pd.read_csv(body)
df.head()

,SEVERITYCODE,X,Y,OBJECTID,INCKEY,COLDETKEY,REPORTNO,STATUS,ADDRTYPE,INTKEY,...,ROADCOND,LIGHTCOND,PEDROWNOTGRNT,SDOTCOLNUM,SPEEDING,ST_COLCODE,ST_COLDESC,SEGLANEKEY,CROSSWALKKEY,HITPARKEDCAR
0,2,-122.323148,47.703140,1,1307,1307,3502005,Matched,Intersection,37475.0,...,Wet,Daylight,NaN,NaN,NaN,10,Entering at angle,0,0,N
1,1,-122.347294,47.647172,2,52200,52200,2607959,Matched,Block,NaN,...,Wet,Dark - Street Lights On,NaN,6354039.0,NaN,11,From same direction - both going straight - bo...,0,0,N
2,1,-122.334540,47.607871,3,26700,26700,1482393,Matched,Block,NaN,...,Dry,Daylight,NaN,4323031.0,NaN,32,One parked--one moving,0,0,N
3,1,-122.334803,47.604803,4,1144,1144,3503937,Matched,Block,NaN,...,Dry,Daylight,NaN,NaN,NaN,23,From same direction - all others,0,0,N
4,2,-122.306426,47.545739,5,17700,17700,1807429,Matched,Intersection,34387.0,...,Wet,Daylight,NaN,4028032.0,NaN,10,Entering at angle,0,0,N

In [4]:
print(df.dtypes)

SEVERITYCODE        int64
X                 float64
Y                 float64
OBJECTID            int64
INCKEY              int64
COLDETKEY           int64
REPORTNO           object
STATUS             object
ADDRTYPE           object
INTKEY            float64
LOCATION           object
EXCEPTRSNCODE      object
EXCEPTRSNDESC      object
SEVERITYCODE.1      int64
SEVERITYDESC       object
COLLISIONTYPE      object
PERSONCOUNT         int64
PEDCOUNT            int64
PEDCYLCOUNT         int64
VEHCOUNT            int64
INCDATE            object
INCDTTM            object
JUNCTIONTYPE       object
SDOT_COLCODE        int64
SDOT_COLDESC       object
INATTENTIONIND     object
UNDERINFL          object
WEATHER            object
ROADCOND           object
LIGHTCOND          object
PEDROWNOTGRNT      object
SDOTCOLNUM        float64
SPEEDING           object
ST_COLCODE         object
ST_COLDESC         object
SEGLANEKEY          int64
CROSSWALKKEY        int64
HITPARKEDCAR       object
dtype: object

INATTENTIONIND:
Lack of attention or distraction.

In [7]:
df['INATTENTIONIND'].value_counts().to_frame()

   INATTENTIONIND
Y           29805

LIGHTCOND:
The light conditions during the collision.

In [10]:
df['LIGHTCOND'].value_counts().to_frame()

                          LIGHTCOND
Daylight                     116137
Dark - Street Lights On       48507
Unknown                       13473
Dusk                           5902
Dawn                           2502
Dark - No Street Lights        1537
Dark - Street Lights Off       1199
Other                           235
Dark - Unknown Lighting          11

ROADCOND:
The condition of the road during the collision.

In [11]:
df['ROADCOND'].value_counts().to_frame()

                ROADCOND
Dry               124510
Wet                47474
Unknown            15078
Ice                 1209
Snow/Slush          1004
Other                132
Standing Water       115
Sand/Mud/Dirt         75
Oil                   64

SPEEDING:
Whether or not speeding was a factor in the collision. (Y/N).

In [12]:
df['SPEEDING'].value_counts().to_frame()

   SPEEDING
Y      9333

UNDERINFL:
Whether or not a driver involved was under the influence of drugs or alcohol.

In [13]:
df['UNDERINFL'].value_counts().to_frame()

   UNDERINFL
N     100274
0      80394
Y       5126
1       3995

WEATHER: 
A description of the weather conditions during the time of the collision.

In [14]:
df['WEATHER'].value_counts().to_frame()

                          WEATHER
Clear                      111135
Raining                     33145
Overcast                    27714
Unknown                     15091
Snowing                       907
Other                         832
Fog/Smog/Smoke                569
Sleet/Hail/Freezing Rain      113
Blowing Sand/Dirt              56
Severe Crosswind               25
Partly Cloudy                   5

Dataframe comparation considering: Weather, Roadcond and Lightcond.

In [19]:
df_Weather=df.filter(['SEVERITYCODE', 'WEATHER', 'ROADCOND','LIGHTCOND'], axis=1)
df_Weather.head()

   SEVERITYCODE   WEATHER ROADCOND                LIGHTCOND
0             2  Overcast      Wet                 Daylight
1             1   Raining      Wet  Dark - Street Lights On
2             1  Overcast      Dry                 Daylight
3             1     Clear      Dry                 Daylight
4             2   Raining      Wet                 Daylight

Discussion:
Weather, Light and Road conditions
There are more occurrences of severe collisions during daylight whereas during the night with the lights on, accidents tend to be less risky. The reason for this, may be related to a more cautious driving during the night which predispose car users to an aware state. Dusk and dawn tend to be related to more severe collisions, maybe because of the visibility reduction while facing the sun directly in the vision zone.

Conclusion:
Extremely dangerous weather and road conditions do not produce a quite significant accident rate, such as snow and ice. However, caution have to be taken with rainy weather and wet roads, since after clear days and dry roads, these are the following conditions in order of importance.
Based on the data on collisions in Seattle from 2004 to the present, there are no relationship between bad weather conditions and wet road conditions that affected collisions. From the data, we see that there were a lot more collisions that happened on dry roads and clear weather conditions. There are much less collisions that happen when weather and road conditions are not that great.